[table]
max_table_height = 155
min_table_height = 40
sitting_height = 70
standing_height = 110

[motor]
up_pin = 17
down_pin = 18

[sensor]
trigger_pin = 4
echo_pin = 27
calibration_file = "hcrso4_calibration.toml"